YG-146:Define color pallettes, spacing and sizing for theme.
Pepcus/yjsgUI pull request #396
Opened 2022-09-09 11:56 UTC by Shivani922

# Related issues
- https://pepcus.atlassian.net/browse/YG-146

2022-09-09 12:15 UTC, pepcus-mohit requested changes

2022-09-09 12:15 UTC, pepcus-mohit commented on src/v2/configs/tenant/GMS/theme.ts
> +		minWidth: '100%',
We will be only having fixed units in this file instead of percentages.
Define a generic fixed width.

2022-09-12 07:03 UTC, Shivani922 commented on src/v2/configs/tenant/GMS/theme.ts
> +		minWidth: '100%',
resolved

2022-09-12 16:54 UTC, pepcus-mohit approved these changes

2022-09-12 17:04 UTC, merged