YG-124-UX:Added style to the attendance module.
Pepcus/yjsgUI pull request #399
Opened 2022-09-15 13:28 UTC by Shivani922

# Related issues
- Added style to the attendance module

2022-09-15 13:41 UTC, pepcus-mohit requested changes

2022-09-15 13:41 UTC, pepcus-mohit commented on src/components/common/Header.jsx
> +				{headerObject.title ? '' : ''}
This change can impact all the headers on the other screen, Make sure other screen headers look good.

2022-09-15 13:41 UTC, pepcus-mohit commented on src/components/common/fields/InputField.jsx
> +	display: flex;
Make sure other input fields on registration page or correction page or login forms are not getting impacted by this.

2022-09-15 15:09 UTC, Shivani922 commented on src/components/common/Header.jsx
> +				{headerObject.title ? '' : ''}
Resolved

2022-09-15 15:14 UTC, Shivani922 commented on src/components/common/fields/InputField.jsx
> +	display: flex;
no it is not impacting anything. On member search, search filled was impacted but i fixed that also.

2022-09-16 08:51 UTC, pepcus-mohit approved these changes

2022-09-16 08:52 UTC, merged