YG-124-Header - Added heading in header.
Pepcus/yjsgUI pull request #402
Opened 2022-09-21 11:40 UTC by Shivani922

![image](https://user-images.githubusercontent.com/80804268/191494921-2ba5f8ce-0f6a-4603-b2ef-f97930ff7dad.png)

2022-09-21 11:49 UTC, pepcus-mohit requested changes

2022-09-21 13:28 UTC, pepcus-mohit requested changes

2022-09-21 13:28 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Ujjain/constants/text.json
> +	"MARK_ATTENDANCE_SUCCESS_MESSAGE": "Attendance of selected student has been successfully marked.",
Instead of replacing this with English text.
Please create another variable here: MARK_ATTENDANCE_SUCCESS_MESSAGE_ENG
and Add the English text there.
Also, this change should be done for all the tenants.

2022-09-21 13:28 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Ujjain/constants/text.json
> +	"MARK_ATTENDANCE_FAILED_MESSAGE": "Failed to mark the attendance of selected students.",
same here.

2022-09-21 15:09 UTC, Shivani922 commented on ui_config/tenant/YJSG-Ujjain/constants/text.json
> +	"MARK_ATTENDANCE_SUCCESS_MESSAGE": "Attendance of selected student has been successfully marked.",
Added English Success/Error text variable.

2022-09-22 11:04 UTC, pepcus-mohit requested changes

2022-09-22 11:04 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Ujjain/routes/splashPage.json
> +							"md": 12,
Please update this on all the tenants json including default

2022-09-22 12:43 UTC, Shivani922 commented on ui_config/tenant/YJSG-Ujjain/routes/splashPage.json
> +							"md": 12,
Updated

2022-09-22 13:21 UTC, pepcus-mohit approved these changes

2022-09-22 13:22 UTC, merged