NO_JIRA: Refactored member visible column config.
Pepcus/yjsgUI pull request #412
Opened 2023-01-30 07:18 UTC by pepcus-priya

# Related issues
-  Refactored member visible column config.

# Proposed changes
- Refactored member visible column config.
- Added Member Info Buttons.

2023-01-30 14:52 UTC, pepcus-mohit requested changes

2023-01-30 14:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberColumnConfig/MemberColumnConfig.tsx
> +import { Modal } from '../../components/design/modal/Modal';
This directory/file should be inside MemberDataGrid directory.

2023-01-30 14:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberConfigSearch/MemberConfigSearch.tsx
> +import { CheckboxLabel } from '../../components/design/form/CustomInputs/FormElements/Checkbox/CheckboxLabel';
This should also reside under MemberDataGrid

2023-01-30 14:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberConfigSearch/MemberConfigSearch.tsx
> +			setThresholdValue('0.0');
Are we updating this threshold value anywhere? If not then no need to create state for it.

2023-01-30 14:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/InvokeMemberRegistration.tsx
> +import { useAPI } from '../../components/hooks';
I've deleted this file in the latest develop. Have you merged latest develop on your branch??

2023-01-30 14:52 UTC, pepcus-mohit commented on src/v2/utils/dataGridUtils.ts
> +import Fuse from 'fuse.js';
we can also move this file to MemberDataGrid directory

2023-01-31 07:44 UTC, pepcus-priya commented on src/v2/utils/dataGridUtils.ts
> +import Fuse from 'fuse.js';
this file already placed inside the utils directory so why are we moving this to MemberDataGrid? Instead can we create MemberDataGrid util directory inside the utils folder and put this file into the same directory?

2023-05-10 09:23 UTC, pepcus-mohit approved these changes

2023-05-10 09:23 UTC, merged