YG-199:  Create card component to display classroom characteristics.
Pepcus/yjsgUI pull request #446
Opened 2023-02-24 13:02 UTC by Shivani922

# Related issues
https://pepcus.atlassian.net/browse/YG-199

# Screenshots
Mobile view
![image](https://user-images.githubusercontent.com/80804268/221185170-aebbebe7-0138-4ea4-bc6c-313bf76d04a1.png)

Tablet View
![image](https://user-images.githubusercontent.com/80804268/221185260-faef0319-3863-48d3-89e0-059ed67b7051.png)

Desktop View
![image](https://user-images.githubusercontent.com/80804268/221185315-4f56924d-37cc-43ae-8943-bb1e302e0d37.png)

2023-02-24 14:11 UTC, pepcus-mohit requested changes

2023-02-24 14:11 UTC, pepcus-mohit commented on src/components/common/Card.jsx
> +const Card = ({ radioValue, cardTitle, cardValue, cardNo }) => {
```suggestion
const ClassroomCard = ({ isSelected, classroomDetails, classroomNo }) => {
```

2023-02-24 14:11 UTC, pepcus-mohit commented on src/components/common/Card.jsx
> +			setSelected(target.value);
This should also return the classroomDetails once selected.

2023-02-24 14:11 UTC, pepcus-mohit commented on src/components/common/Card.jsx
> +						<StyledCardInfo>
Iterate through classroomDetails here using map and render key value pairs.

2023-02-24 14:11 UTC, pepcus-mohit commented on src/components/common/Card.jsx
> +					<StyledCardHeadingContainer>{cardNo}</StyledCardHeadingContainer>
```suggestion
					<StyledCardHeadingContainer>{classroomNo}</StyledCardHeadingContainer>
```

2023-02-24 18:46 UTC, Shivani922 commented on src/components/common/Card.jsx
> +const Card = ({ radioValue, cardTitle, cardValue, cardNo }) => {
Resolved

2023-02-24 18:47 UTC, Shivani922 commented on src/components/common/Card.jsx
> +			setSelected(target.value);
Resolved

2023-02-24 18:47 UTC, Shivani922 commented on src/components/common/Card.jsx
> +						<StyledCardInfo>
Resolved

2023-02-24 18:47 UTC, Shivani922 commented on src/components/common/Card.jsx
> +					<StyledCardHeadingContainer>{cardNo}</StyledCardHeadingContainer>
Resolved

2023-02-24 19:15 UTC, pepcus-mohit requested changes

2023-02-24 19:15 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +							<StyledCardInfo key={details.id}>
I think this will render each and every key-value pair available on the classroom details. We need to make it limited to just 4 rows that are mentioned in the figma.
So better make it static. and render only the required set of data.
Also we need to figure out first whether this classroomDetails should be an object or an array by looking at the API response. So let's hold on to this until then.

2023-02-24 19:15 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +const ClassroomCard = ({ isSelected, classroomDetails, classroomNo }) => {
```suggestion
const ClassroomCard = ({ isSelected, classroomDetails, classroomNo, onCardSelection }) => {
```

2023-02-24 19:15 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +			return classroomDetails;
By returning the data from here I mean, returning the data in a callback fn prop.
```suggestion
		 onCardSelection(classroomDetails);
```

2023-02-27 10:08 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +const ClassroomCard = ({ isSelected, classroomDetails, classroomNo }) => {
resolved

2023-02-27 10:08 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +			return classroomDetails;
resolved

2023-02-27 15:35 UTC, pepcus-mohit approved these changes

2023-02-27 15:35 UTC, merged