YG-221: Added an info icon and highlighted the text when the strength is getting full.
Pepcus/yjsgUI pull request #453
Opened 2023-02-28 14:39 UTC by Shivani922

# Related issues
https://pepcus.atlassian.net/browse/YG-221

# Screenshots
![image](https://user-images.githubusercontent.com/80804268/221886205-595294ed-0329-48ac-9565-1663c607909b.png)
![image](https://user-images.githubusercontent.com/80804268/221886319-070980b4-e640-4701-a2c9-6ccac9e62368.png)
![image](https://user-images.githubusercontent.com/80804268/221886367-ffcc8697-878a-41d4-9661-751b05670f74.png)

2023-02-28 15:32 UTC, pepcus-mohit requested changes

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +							<StyledCardInfo className="danger-color">
Do not use className on StyledComponents
```suggestion
							<StyledCardInfo currentStrength={currentStrength} totalStrength={totalStrength}>
```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +	.danger-color {
```suggestion
	
```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +		color: #e62c14 !important;
```suggestion
		color: ${totalStrength - currentStrength < = 5 ? 'red' : 'black'};
```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +	const [minSeatDifference, setMinSeatDifference] = useState(false);
Not Needed
```suggestion
	
```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +	const [equal, setEqual] = useState(false);
Not needed
```suggestion

```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +												: `Only ${strengthDifference} seats left in the classroom.`
Get these messages from constants in the JSON.

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +										message={
```suggestion
										message={
										totalStrength - currentStrength < = 5 ? ONlY_SEATS_LEFT_MSG : totalStrength - currentStrength <= 0 ? NO_SEATS_LEFT_MSG : null
```

2023-02-28 15:32 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +	React.useEffect(() => {
Not needed
```suggestion
	
```

2023-03-01 08:01 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +							<StyledCardInfo className="danger-color">
resolved

2023-03-01 08:01 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +	.danger-color {
Resolved

2023-03-01 08:02 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +		color: #e62c14 !important;
Resolved

2023-03-01 08:02 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +	const [minSeatDifference, setMinSeatDifference] = useState(false);
Resolved

2023-03-01 08:02 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +	const [equal, setEqual] = useState(false);
Resolved

2023-03-01 08:02 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +												: `Only ${strengthDifference} seats left in the classroom.`
Resolved

2023-03-01 08:03 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +										message={
Resolved

2023-03-01 08:03 UTC, Shivani922 commented on src/components/common/ClassroomCard.jsx
> +	React.useEffect(() => {
Resolved

2023-03-01 08:16 UTC, pepcus-mohit approved these changes

2023-03-01 08:16 UTC, merged