YG-201: UI - Fetch Classroom records with the level and assign classroom to student.
Pepcus/yjsgUI pull request #463
Opened 2023-03-02 20:12 UTC by pepcus-priya

# Related issues
- Fetch Classroom records with the level and assign classroom to student.

# screen view
https://user-images.githubusercontent.com/107912206/222541443-815c3c0c-f577-49d4-a1dd-837b9179dccf.mp4

2023-03-03 06:53 UTC, pepcus-mohit requested changes

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
> +		if (checked) {
Why do we need this condition?

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/common/ClassroomCard.jsx
>  	classroomNo,
rather than passing all these props like classroomNo, totalStrength, currentStrength etc. Can we just send entire classroomDetails obj here and then extract out the details here only.

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +	const [data, setData] = useState([]);
Can we have some non-generic name instead of data.

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +				return { ...classRoom, isSelected: true };
same here ?

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +		const res = await fetchClassRoom({ secretKey: AUTHTOKEN.secretKey });
This should be fetchClassroom by level ?

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +		fetchData();
This should not run on every component initialization, it should run when the level is selected.

2023-03-03 06:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/classRoomApi.js
> +export const fetchClassRoom = async ({ secretKey }) => {
```suggestion
export const fetchClassRoomByLevel = async ({ level, secretKey }) => {
```

2023-03-06 14:46 UTC, pepcus-priya commented on src/components/routeComponents/memberRegistrationCorrectionForm/CorrectionsForm.jsx
> -							renderSubmitButtons={renderSubmitButtons}
No

2023-03-06 18:11 UTC, pepcus-mohit requested changes

2023-03-06 18:11 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +		setClassRoomList(res);
What if this API gets failed, shouldn't we handle error here?
```js
     if (res) {
		setClassRoomList(res);
     } else {
        setAlert ('Unable to fetch classrooms at the moment.')
    }
```

2023-03-06 18:11 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +								formData: { classAttended: updatedLevel },
create a handler method for this

2023-03-06 18:11 UTC, pepcus-mohit commented on src/components/routeComponents/memberRegistrationCorrectionForm/AssignLevelAndClassroomModal.jsx
> +									onSubmit();
```suggestion
									onClick={onSubmit}
```

2023-03-07 12:02 UTC, pepcus-mohit approved these changes

2023-03-07 12:02 UTC, merged