YG-258: Resolve column alignment issue.
Pepcus/yjsgUI pull request #485
Opened 2023-03-14 16:52 UTC by Shivani922

Relatable Issue
https://pepcus.atlassian.net/browse/YG-258

# Screenshots
![image](https://user-images.githubusercontent.com/80804268/225078764-a47c54fc-6018-4c3e-bdfc-ef6591cb54f5.png)
![image](https://user-images.githubusercontent.com/80804268/225078464-4d5d8f68-6784-4382-99bf-d80f6b89991f.png)

2023-03-14 18:53 UTC, pepcus-mohit requested changes

2023-03-14 18:53 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/columnConfig/ColumnConfiguration.jsx
> +		const chunkLength = Math.ceil(columnList.length / 1);
No need to divide it by 1. Haha!
```suggestion
		const chunkLength = Math.ceil(columnList.length);
```

2023-03-15 05:28 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/columnConfig/ColumnConfiguration.jsx
> +		const chunkLength = Math.ceil(columnList.length / 1);
Removed.

2023-03-15 06:38 UTC, pepcus-mohit approved these changes

2023-03-15 06:39 UTC, merged