YG-296: Added attendance model button and model to the admin grid.
Pepcus/yjsgUI pull request #511
Opened 2023-03-30 06:12 UTC by Shivani922

# Related issues
https://pepcus.atlassian.net/browse/YG-296

# Screenshots

https://user-images.githubusercontent.com/80804268/228745459-644ed819-a6ad-43ee-a23b-bcf9eb1e81ff.mp4

2023-03-30 13:37 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx
> +							isEmpty={isEmpty(selectedMembers) ? 'true' : 'false'}>
No need to send booleans in strings.
```suggestion
							isEmpty={isEmpty(selectedMembers) ? true : false}>
```

2023-03-30 13:41 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceDisplayCard.jsx
> +							<StyledCardInfoTitle>Total</StyledCardInfoTitle>
Can we get these strings like Total, Present etc from JSON constants.

2023-03-30 13:42 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const renderModel = () => {
```suggestion
	const renderModal = () => {
```

2023-03-30 13:42 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const openModel = () => {
```suggestion
	const openModal = () => {
```

2023-03-30 13:42 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const [isModelOpen, setIsModelOpen] = useState(false);
```suggestion
	const [isModalOpen, setIsModalOpen] = useState(false);
```

2023-03-30 13:43 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +						<StyledModelBody>
```suggestion
						<StyledModalBody>
```

2023-03-30 13:46 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +			<StyledModelLink onClick={openModel}>Attendance Model</StyledModelLink>
Get these strings from JSON constants.
```suggestion
			<StyledModelLink onClick={openModel}>Attendance Report</StyledModelLink>
```

2023-03-30 13:48 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/ModelHeader.jsx
There is a typo in directory name.
Please Rename this file and the parent directory to
attendanceReportModal/ModalHeader.jsx

2023-03-30 13:49 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/markSelectedMembersAttendance/MarkSelectedMembersAttendance.jsx
> +					isEmpty={isEmpty(selectedMembers) ? 'true' : 'false'}
```suggestion
					isEmpty={isEmpty(selectedMembers) ? true : false}
```

2023-03-31 08:15 UTC, Shivani922 commented on src/components/common/Accordion/Accordion.jsx
> +const Accordion = ({ children, day, totalAttendance }) => {
Resolve

2023-03-31 08:16 UTC, Shivani922 commented on src/components/common/Accordion/Accordion.jsx
> +						{day} <span>{totalAttendance}</span>
replaced by title and sub title.

2023-03-31 08:16 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/SelectedMembersActionWrapper.jsx
> +							isEmpty={isEmpty(selectedMembers) ? 'true' : 'false'}>
resolved

2023-03-31 08:16 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceDisplayCard.jsx
> +							<StyledCardInfoTitle>Total</StyledCardInfoTitle>
resolved

2023-03-31 08:16 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const renderModel = () => {
resolved

2023-03-31 08:17 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const openModel = () => {
resolved

2023-03-31 08:17 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +	const [isModelOpen, setIsModelOpen] = useState(false);
resolved

2023-03-31 08:17 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +						<StyledModelBody>
Resolved

2023-03-31 08:17 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/AttendanceReportModel.jsx
> +			<StyledModelLink onClick={openModel}>Attendance Model</StyledModelLink>
Resolved

2023-03-31 08:18 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModel/ModelHeader.jsx
Resolved

2023-03-31 08:18 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/markSelectedMembersAttendance/MarkSelectedMembersAttendance.jsx
> +					isEmpty={isEmpty(selectedMembers) ? 'true' : 'false'}
Resolved

2023-03-31 08:24 UTC, pepcus-mohit requested changes

2023-03-31 08:24 UTC, pepcus-mohit commented on src/components/common/Accordion/Accordion.jsx
> +						{title} <span>{subTitle}</span>
Try to pass the title as a component.

2023-04-03 07:46 UTC, Shivani922 commented on src/components/common/Accordion/Accordion.jsx
> +						{title} <span>{subTitle}</span>
added a accordion title component in it.

2023-04-03 12:20 UTC, pepcus-mohit requested changes

2023-04-03 12:20 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceResportModal/AttendanceReportModal.jsx
> +										Day1 <span>combination attendance</span>
We should get these strings from JSON constants
```suggestion
										Day1 <span>combined attendance</span>
```

2023-04-06 10:59 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModal/AttendanceReportModal.jsx
> +								title={
Implemented the API response

2023-04-06 11:00 UTC, Shivani922 commented on src/components/routeComponents/memberInformationGrid/attendanceResportModal/AttendanceReportModal.jsx
> +										Day1 <span>combination attendance</span>
Resolved

2023-04-06 11:05 UTC, pepcus-mohit requested changes

2023-04-06 11:05 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceReportModal/AttendanceReportModal.jsx
> +const AttendanceData = {
The latest changes are available in QA now, Can we remove this mock and replace it with API call.

2023-04-06 11:05 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceReportModal/AttendanceReportModal.jsx
> +													{methodData.totalStudents})
Use template literals

2023-04-06 11:05 UTC, pepcus-mohit commented on src/components/routeComponents/memberInformationGrid/attendanceReportModal/AttendanceReportModal.jsx
> +	const AttendanceMethodData = getFormattedData(AttendanceData);
```suggestion
	const formattedAttendanceResults = getFormattedData(AttendanceData);
```

2023-04-08 15:32 UTC, pepcus-mohit approved these changes

2023-04-08 15:55 UTC, pepcus-mohit approved these changes

2023-04-08 16:03 UTC, merged