YG-311: Manage Classroom and Day access as per the user type
Pepcus/yjsgUI pull request #524
Opened 2023-04-06 18:11 UTC by pepcus-akshita

# Related issues
- Manage Classroom and Day access as per the user type

https://user-images.githubusercontent.com/113973515/230460636-05b2d74f-fc55-4363-9173-fa410c35c538.mp4

# Screenshots

2023-04-06 18:15 UTC, pepcus-akshita commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
> +						"Day 1 (07-04-2023)",
Changed the date for testing purpose only for one day.
Change Require before merging.

2023-04-06 18:16 UTC, pepcus-akshita commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
> +						"Day 1 (07-04-2023)",
Changed the date for testing purpose only for one day.
Change Require before merging.

2023-04-06 18:21 UTC, pepcus-mohit requested changes

2023-04-06 18:21 UTC, pepcus-mohit commented on src/components/routeComponents/markAttendance/FetchRoomAttendanceForm.jsx
> +	console.log('# formdata in fetchroomattendance', formData);
Remove console
```suggestion
	
```

2023-04-06 18:21 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
> +						"Day 1 (07-04-2023)",
This should not be changed.
Also Day 8 should be "Day 8 (08-05-2023)"

2023-04-06 18:21 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
JSON formatting?

2023-04-06 18:21 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
> +						"Day 2 (01-05-2023)",
```suggestion
						"Day 2 (30-04-2023)",
```

2023-04-06 18:21 UTC, pepcus-mohit commented on ui_config/tenant/YJSG-Indore/routes/splashPage.json
> +						"Day 8 (07-05-2023)"
```suggestion
						"Day 8 (08-05-2023)"
```

2023-04-13 07:39 UTC, pepcus-mohit approved these changes

2023-04-13 07:39 UTC, merged