YG-400: UI - V2 : Migrating UI Home Route on V2
Pepcus/yjsgUI pull request #596
Opened 2023-05-19 11:12 UTC by pepcus-akshita

# Related issues
- Migrated Home route on V2

# Screenshots

https://github.com/Pepcus/yjsgUI/assets/113973515/c2ea4f26-cfe1-4f75-89ca-20e71fa325cf

2023-05-19 12:21 UTC, pepcus-mohit requested changes

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +	const getUpdatedMetaData = () => {
If we define the purpose in the method name that would be great.
```suggestion
	const replaceCustomComponentInMeta = () => {
```

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +				<form>
Use Formik for every form

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +							<input
Use Input Component to display radios

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +								value="N"
same here

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +							<label htmlFor="N">{NO_ALTERNATE_HINDI}</label>
We also have label component. Use that only

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +			const prevMemberData = initialGridData[index];
Well these are the complex logics that are really difficult to update at a later point in time. I really want to break them down in smaller chunks in v2.
For example, This method is dealing with 2 logics:

1. Updating optIn in the members
2. calling the api

I think we can segregate the logic as per the points mentioned above.

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +import Row from 'pepcus-core/lib/Row';
Avoid pepcus core

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +const NewRegistrationPageLink = ({ strings, onClickBackBtn }) => {
This can be renamed to something else as it is rendering a lot of content than just a link.

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +		border-radius: 4px;
Use theme spacing wherever you can

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +	font-size: 16px;
Try not to use external fontSize, Use theme fontsizes instead

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +	color: rgb(88, 100, 251);
Use colors mentioned in theme only

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +	font-weight: 400;
I would recommend to use textComponents everywhere we are displaying texts.

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +			<DescriptionContainerStyled>
Use TextComponents

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/HomeScreen.tsx
> +		font-size: 17px;
Use TextComponents, Avoid external styling as much as possible.

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +				<DescriptionContainerStyled>{MEMBER_DETAILS}</DescriptionContainerStyled>
Use Text Components

2023-05-19 12:21 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationPrompt.jsx
> +const InputStyled = styled.div`
Create a radio Input component or use the existing one instead.

2023-05-23 12:28 UTC, pepcus-akshita commented on src/v2/layouts/HomeScreen/NewRegistrationPageLink.jsx
> +const NewRegistrationPageLink = ({ strings, onClickBackBtn }) => {
It is just rendering the New registration button, and the button redirects to member-register route.

2023-05-25 15:00 UTC, pepcus-mohit commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +			const updateData = (list) => {
Looks like there is redundant function call
```suggestion
			const updatedData = gridData?.map((data) => {
```

2023-05-26 06:35 UTC, pepcus-akshita commented on src/v2/components/design/form/formTypes.ts
> +	checked?: boolean;
No, we can use the same prop. I'll update it.

2023-05-26 11:28 UTC, pepcus-akshita commented on src/v2/layouts/HomeScreen/ExistingRegistrationTable.jsx
> +		const onSubmit = () => {};
No, we do not have a submit button, just radio buttons are rendering. So, onSubmit is not required.

2023-05-26 11:53 UTC, pepcus-akshita commented on src/v2/layouts/HomeScreen/NewMemberRegistration.jsx
> +const LinkStyled = styled(Link)(() => css``);
It is written empty for shivani to add styling as per requirement. Right now proper styling is not done here.

2023-05-26 12:05 UTC, pepcus-akshita commented on src/v2/components/design/loader/CustomLoader.jsx
> +					<div className="lds-spinner">
This customLoader component is updated in Priya's PR already.

2023-05-26 15:06 UTC, pepcus-mohit approved these changes

2023-05-26 15:06 UTC, merged