YG-404: Resolve styling issues in registration form.
Pepcus/yjsgUI pull request #597
Opened 2023-05-24 08:39 UTC by Shivani922

# Related issues
https://pepcus.atlassian.net/browse/YG-404

# Screenshots

https://github.com/Pepcus/yjsgUI/assets/80804268/7fa96781-6a3a-4034-b0c5-c5fcfdc368f1

2023-05-25 06:26 UTC, pepcus-mohit requested changes

2023-05-25 06:26 UTC, pepcus-mohit commented on src/v2/components/design/form/CustomInputs/FormElements/Dropdown/Dropdown.tsx
> +		background: #ffffff;
use color.white from theme

2023-05-25 06:26 UTC, pepcus-mohit commented on src/v2/components/design/form/CustomInputs/FormElements/Dropdown/Dropdown.tsx
> +		z-index: 100;
There is no track of z-indexes in the theme, Can you create an object inside theme for zIndex, same as we are using color, spacing then use it here:
Example: In theme.ts

zIndex: {
   dropdown: 100,
}

And then use ${zIndex.dropdown} in Styled Components.

2023-05-25 06:26 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		padding: 20px 10px 0;
Can we use spacing here, if possible?

2023-05-25 06:26 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistrationForm.tsx
> +	@media (max-width: 767px) {
We also have mediaQueries config in theme.ts, You can also use that here.

2023-05-25 07:54 UTC, Shivani922 commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		padding: 20px 10px 0;
resolved

2023-05-25 07:55 UTC, Shivani922 commented on src/v2/components/design/form/CustomInputs/FormElements/Dropdown/Dropdown.tsx
> +		z-index: 100;
resolved

2023-05-25 08:03 UTC, pepcus-mohit requested changes

2023-05-25 08:03 UTC, pepcus-mohit commented on src/v2/configs/tenant/default/theme.ts
> +		label: '1',
Use number instead of strings

2023-05-25 08:03 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		border-color: rgb(230, 234, 238);
Use theme.color instead

2023-05-25 08:03 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		box-shadow: rgba(221, 225, 239, 0.2) 0 3px 5px -1px,
Use theme.color

2023-05-25 08:03 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		background-color: rgb(245, 245, 245);
Use theme.color

2023-05-25 08:03 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistrationForm.tsx
> +		margin-top: 12px;
Try to use spacing here.

2023-05-25 14:44 UTC, Shivani922 commented on src/v2/layouts/MemberRegistration/MemberRegistrationForm.tsx
> +		margin-top: 12px;
resolve

2023-05-25 14:44 UTC, Shivani922 commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		background-color: rgb(245, 245, 245);
resolve

2023-05-25 14:44 UTC, Shivani922 commented on src/v2/layouts/MemberRegistration/MemberRegistration.tsx
> +		border-color: rgb(230, 234, 238);
resolved

2023-05-25 14:44 UTC, Shivani922 commented on src/v2/configs/tenant/default/theme.ts
> +		label: '1',
resolved

2023-05-25 15:04 UTC, pepcus-mohit requested changes

2023-05-25 15:04 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistration/MemberRegistrationForm.tsx
> +		button {
Can we not target the global class in the Styled components please?

2023-05-25 15:11 UTC, Shivani922 commented on src/v2/layouts/MemberRegistration/MemberRegistrationForm.tsx
> +		button {
We are not targeting the global class here.. actually i need to change some button styling to this particular place that's why i put here not in button component because if i put in button component it will reflect all over.

and button is not a class it is tag.

2023-05-28 08:01 UTC, pepcus-mohit approved these changes

2023-05-28 08:01 UTC, pepcus-mohit approved these changes

2023-05-28 08:01 UTC, merged