YG-407: Refactored Attendance Report Modal.
Pepcus/yjsgUI pull request #598
Opened 2023-05-25 07:01 UTC by pepcus-priya

# Related issues
- V2 > Refactored Attendance Report Modal.

# Proposed changes
- used useContext and Text Components.
- Removed pepcus-core library
- Replaced Class Component to Function Component.

# Screenshots
![image](https://github.com/Pepcus/yjsgUI/assets/107912206/942b94be-c3c5-4331-93b0-8c343dc46e31)
![image](https://github.com/Pepcus/yjsgUI/assets/107912206/dd557c98-5e89-4aed-bcb2-a00d4c0d6b9f)

2023-05-25 07:52 UTC, pepcus-mohit requested changes

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/Files/fileStyled.js
> +	margin-left: 10px;
Use theme.spacing

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/Files/fileStyled.js
> +	color: ${(props) => (props.isview === 'true' ? '#0868ac' : '#898787')};
Use theme.color instead of hard codings

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/design/modal/Modal.tsx
> +	background-color: rgba(0, 0, 0, 0.5);
Use theme.color instead

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/design/modal/ModalHeader.jsx
> +	background: rgb(88, 100, 251);
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/loader/CustomLoader.jsx
> +			<div className="lds-css">
No classnames, Use StyledComponents only

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +					classRooms: classRooms(),
```suggestion
					classRooms,
```

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +import { useContext, useEffect, useState } from 'react';
This component is too long, Try to accommodate the component's content in 100 lines of code.

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +						<ModalHeader>
We can move the Modal Content part in separate component to shorten the component's length.

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +								<StyledHeaderTitle>
Try to use TextComponents wherever we're displaying texts

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +	color: rgb(255, 255, 255);
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +												<StyledSpan>
Use Text Components instead

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +		border-right: 1px solid #e5e5e5;
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +		background: #888;
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/AttendanceReportModal/AttendanceReportModal.jsx
> +	max-height: 76vh;
Keep consistent units, it should be px throughout the app.

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberDataGrid/MemberInfoData.tsx
> +	console.log('####response', studentList);
Remove console.

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberDataGrid/MemberInfoData.tsx
>  import isEmpty from 'lodash/isEmpty';
Break this component into multiple components, A component should not exceed 100-125 lines

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberDataGrid/MemberInfoData.tsx
>  				<MemberConfigSearch onSearch={onSearch} clearSearch={clearSearch} />
Move Search functionality to another component

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberDataGrid/MemberInfoData.tsx
>  				)}
Also move the column config handling in another component.

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/MemberRegistrationCorrection/MemberCorrectionResponseModal.tsx
> +import Modal from '../../components/design/modal/Modal';
```suggestion
import { Modal } from '../../components/design/modal/Modal';
```

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +	border: none rgb(219, 215, 214);
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +	background: linear-gradient(to top, rgb(235, 235, 236), rgb(235, 235, 236));
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +	background-color: #f9f9f9;
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +const SelectedMembersWrapper = () => {
Can we rename this component to more specific name?

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/components/design/modal/Modal.tsx
> +const Modal = ({ children, isShowing, closeModal }: modalProps) => {
isShowing prop seems redundant here. We can manage the Modal visibility from parent component itself.
```suggestion
const Modal = ({ children, onCloseModal }: modalProps) => {
```

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +    background: #dbd7d6;
Use theme.color

2023-05-25 07:52 UTC, pepcus-mohit commented on src/v2/layouts/SelectedMembersWrapper/SelectedMembersWrapper.jsx
> +			background-color: #f1f1f1;
Use theme.color

2023-05-29 08:04 UTC, pepcus-ankit commented
@pepcus-priya : Please try to follow coding practices. @pepcus-mohit : Could you point her to the coding practices we follow.

2023-05-30 07:43 UTC, merged