YG-434: Added Print Modal and Print Now feature on member search page.
Pepcus/yjsgUI pull request #620
Opened 2023-06-29 09:10 UTC by pepcus-akshita

# Related issues
-  Added Print Modal and Print Now feature on member search page.

# Proposed changes
- Print Now option is enabled when any student is selected and it prints the Id card for selected students(s).

# Screenshots

<img width="960" alt="image" src="https://github.com/Pepcus/yjsgUI/assets/113973515/20b82d4d-7b92-4cf0-81f8-0a58caf36966">

<img width="956" alt="image" src="https://github.com/Pepcus/yjsgUI/assets/113973515/e61a4e60-b6ad-40dd-9caf-8e1f4f2f4efa">

<img width="959" alt="image" src="https://github.com/Pepcus/yjsgUI/assets/113973515/92da43ce-9022-4356-a89d-b25fa87661ed">

2023-06-29 14:49 UTC, pepcus-mohit requested changes

2023-06-29 14:49 UTC, pepcus-mohit commented on src/v2/configs/tenant/YJSG-Indore/strings.json
> +	"COORDINATOR_NAME": "Coordinator name: ",
Do not include symbols on strings.json.
```suggestion
	"COORDINATOR_NAME": "Coordinator name",
```

2023-06-29 14:49 UTC, pepcus-mohit commented on src/v2/layouts/MemberDataGrid/MemberDataGridContainer.jsx
> +				<Header showLogo={true}>
Can you coordinate with Shivani as she has made some changes in the Buttons on Admin Grid and that already includes a Logout button.
So I think we don't need the Logout button here. May be we can replace the Buttons Logout link implementation with this logout button component.

2023-06-29 14:49 UTC, pepcus-mohit commented on src/v2/utils/dataGridUtils.js
> +export const getFormattedMemberId = ({ memberId }) => {
How about this ?
String(num).padStart(4,'0')

2023-06-30 05:25 UTC, pepcus-akshita commented on src/v2/layouts/MemberDataGrid/MemberDataGridContainer.jsx
> +				<Header showLogo={true}>
As per discussion, we don't need this logout component here. So removing this from here.

2023-06-30 06:55 UTC, pepcus-mohit approved these changes

2023-06-30 06:55 UTC, merged